INFO 2025-05-19 21:08:35,856 views 3372 5852 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-19 21:08:41,025 views 3372 5852 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-19 21:08:54,712 views 3372 5852 Usuario 'ian1990' intentando acción 'delete' en rutas protegidas (Ruta add: '/ian1990/', Ruta del: '/ian1990/casa').
INFO 2025-05-19 21:08:54,719 views 3372 5852 Ruta '/ian1990/casa' eliminada del UserJSON de 'ian1990'.
INFO 2025-05-19 21:08:54,720 utils 3372 5852 Generando configuración global de Caddy…
INFO 2025-05-19 21:08:54,723 utils 3372 5852 Ruta catch-all a Django configurada con dial: ':8000'.
INFO 2025-05-19 21:08:54,725 utils 3372 5852 Configuración de Caddy guardada en: C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\caddy_configs\caddy.json
ERROR 2025-05-19 21:08:56,790 utils 3372 5852 No se pudo conectar con la API de Caddy en http://127.0.0.1:2019. ¿Está Caddy corriendo?
WARNING 2025-05-19 21:08:56,791 views 3372 5852 Fallo en la recarga de Caddy tras eliminar ruta protegida para 'ian1990': Error: No se pudo conectar con el servidor Caddy. Por favor, verifica su estado.
INFO 2025-05-19 21:09:18,668 views 3372 16440 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-19 21:09:29,859 views 3372 16440 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-20 15:35:42,210 views 12188 18528 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-20 17:10:54,404 views 20368 27260 Usuario 'ian1990' cerrando sesión.
INFO 2025-05-20 17:11:00,594 views 20368 27260 Usuario 'ian1990' ha iniciado sesión correctamente.
INFO 2025-05-20 17:11:05,049 views 20368 27260 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-20 17:11:12,038 views 20368 27260 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Target: '').
INFO 2025-05-20 17:42:02,264 views 28020 28640 Usuario 'ian1990' intentando acción 'add' en dominios proxy (Dominio: 'ian.com', Destino: '192.168.1.100:8080').
INFO 2025-05-20 17:42:02,273 views 28020 28640 Dominio proxy 'ian.com' a '192.168.1.100:8080' añadido para 'ian1990'.
INFO 2025-05-20 17:42:02,273 utils 28020 28640 [Add domain proxy by ian1990] Generando configuración global de Caddy…
INFO 2025-05-20 17:42:02,277 utils 28020 28640 Ruta catch-all a Django configurada con dial: ':8000'.
INFO 2025-05-20 17:42:02,279 utils 28020 28640 Configuración de Caddy guardada en: C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\caddy_configs\caddy.json
ERROR 2025-05-20 17:42:04,322 utils 28020 28640 [Add domain proxy by ian1990] No se pudo conectar con la API de Caddy en http://127.0.0.1:2019. ¿Está Caddy corriendo?
WARNING 2025-05-20 17:42:04,323 views 28020 28640 Fallo en la recarga de Caddy tras añadir dominio proxy para 'ian1990': Error: No se pudo conectar con el servidor Caddy. Por favor, verifica su estado.
ERROR 2025-05-20 17:42:28,560 views 28020 28640 Error CRÍTICO en home_view para 'ian1990'.
Traceback (most recent call last):
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\cloudguardian\views.py", line 218, in home_view
    return render(request, 'home.html', context)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dominios_proxy' not found. 'dominios_proxy' is not a valid view function or pattern name.
ERROR 2025-05-20 17:42:38,423 views 28020 28640 Error CRÍTICO en home_view para 'ian1990'.
Traceback (most recent call last):
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\cloudguardian\views.py", line 218, in home_view
    return render(request, 'home.html', context)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dominios_proxy' not found. 'dominios_proxy' is not a valid view function or pattern name.
INFO 2025-05-20 17:53:36,185 views 5292 2836 Usuario 'ian1990' cerrando sesión.
INFO 2025-05-20 17:53:43,397 views 5292 17996 Usuario 'ian1990' ha iniciado sesión correctamente.
INFO 2025-05-20 17:54:01,582 views 5292 17996 Usuario 'ian1990' cerrando sesión.
INFO 2025-05-20 17:54:09,332 views 5292 17996 Usuario 'ian1990' ha iniciado sesión correctamente.
INFO 2025-05-20 18:02:59,329 views 5292 27052 Usuario 'ian1990' intentando acción 'delete' en destinos externos (Alias: '', Destino: '').
INFO 2025-05-20 18:03:05,412 views 5292 27052 Usuario 'ian1990' intentando acción 'delete' en dominios proxy (Dominio: 'ian.com', Destino: '').
INFO 2025-05-20 18:03:05,421 views 5292 27052 Dominio proxy 'ian.com' eliminado para 'ian1990'.
INFO 2025-05-20 18:03:05,422 utils 5292 27052 [Delete domain proxy by ian1990] Generando configuración global de Caddy…
INFO 2025-05-20 18:03:05,425 utils 5292 27052 Ruta catch-all a Django configurada con dial: ':8000'.
INFO 2025-05-20 18:03:05,427 utils 5292 27052 Configuración de Caddy guardada en: C:\Users\USUARIO\Desktop\fct\FIREWALL\cloudguardian-deploy\backend\caddy_configs\caddy.json
ERROR 2025-05-20 18:03:07,462 utils 5292 27052 [Delete domain proxy by ian1990] No se pudo conectar con la API de Caddy en http://127.0.0.1:2019. ¿Está Caddy corriendo?
WARNING 2025-05-20 18:03:07,462 views 5292 27052 Fallo en la recarga de Caddy tras eliminar dominio proxy para 'ian1990': Error: No se pudo conectar con el servidor Caddy. Por favor, verifica su estado.
INFO 2025-05-20 18:04:40,615 views 5292 27052 Usuario 'ian1990' cerrando sesión.
INFO 2025-05-20 18:05:55,209 views 5292 27052 Usuario 'ian1990' ha iniciado sesión correctamente.
INFO 2025-05-20 18:06:05,096 views 5292 27052 Usuario 'ian1990' cerrando sesión.
INFO 2025-05-20 18:09:39,227 views 5292 1304 Usuario 'ian1990' ha iniciado sesión correctamente.
